import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Navbar from "../components/Navbar/Navbar";
import Swiperr from "../components/Swiperr";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full w-full font-fraunces bg-gray-300">
        <Navbar />
        <div>
          <br />
          <br />
        </div>
        <Swiperr />
        <section>
          <Link
            href="aboutus"
            className="flex justify-center text-2xl md:text-4xl text-red-500 uppercase mb-10 mt-10 font-semibold"
          >
            Who We Are
          </Link>
          <div className="bg-black text-white py-10 mt-5 px-5">
            <h1 className="mb-3 text-center font-bold text-lg md:text-3xl">Our Mission </h1>

            <p className="text-center md:text-xl">
              {" "}
              Our mission is to make educational research projects readily
              accessible to students, educators, and researchers in the
              Educational Technology field. We believe that sharing knowledge
              through research is essential for academic growth and development.
            </p>
            <h1 className="mt-3 mb-3 text-center font-bold md:text-3xl text-lg">
              Our Vision
            </h1>

            <p className="text-center md:text-xl">
              {" "}
              We envision a world where educational research projects are easily
              accessible and available to anyone who needs them. We hope to
              contribute to this vision by providing a platform for
              undergraduate students to share their research with a wider
              audience.
            </p>
          </div>
          <h2 className="text-2xl mt-5 font-semibold text-red-500 md:text-3xl text-center">
            ---LATEST PROJECTS---
          </h2>
          <div className="flex flex-col justify-center">
            <div className="mt-10 md:flex-row md:flex md:gap-7 mx-auto">
              <Link href="/compsciedu">
                <div className="h-[40vh] w-[40vh] relative">
                  {" "}
                  <div className=" w-full bottom-16 absolute z-20">
                    {" "}
                    <h1 className="text-2xl font-semibold text-white text-center">
                      Computer Science Education
                    </h1>
                  </div>{" "}
                  <Image
                    className="h-full w-full object-cover object-top"
                    src={"/compsciedu.jpeg"}
                    width={500}
                    height={500}
                    alt=""
                  />{" "}
                  <div className="absolute top-0 left-0 w-full h-full bg-black opacity-50 z-10"></div>
                </div>
              </Link>
              <Link href="/edutech">
                <div className="h-[40vh] w-[40vh] relative md:mt-0 mt-5 mb-5">
                  {" "}
                  <div className=" w-full bottom-16 absolute z-20">
                    {" "}
                    <h1 className="text-2xl font-semibold text-white text-center">
                      Educational Technology
                    </h1>
                  </div>{" "}
                  <Image
                    className="h-full w-full object-cover object-top"
                    src={"/edutech.jpeg"}
                    width={500}
                    height={500}
                    alt=""
                  />{" "}
                  <div className="absolute top-0 left-0 w-full h-full bg-black opacity-50 z-10"></div>
                </div>
              </Link>
              <Link href="/techedu">
                <div className="h-[40vh] w-[40vh] relative">
                  {" "}
                  <div className=" w-full bottom-16 absolute z-20">
                    {" "}
                    <h1 className="text-2xl font-semibold text-white text-center">
                      Technology Education
                    </h1>
                  </div>{" "}
                  <Image
                    className="h-full w-full   object-cover object-top"
                    src={"/techedu.jpeg"}
                    width={500}
                    height={500}
                    alt=""
                  />{" "}
                  <div className="absolute top-0 left-0 w-full h-full bg-black opacity-50 z-10"></div>
                </div>
              </Link>
            </div>
          </div>
        </section>
      </main>
      <p className="text-center font-mono font-semibold">EDUTECH © 2023 </p>
    </>
  );
}
